name: Slack Notification
on:
  release:
    types: [published]
  
  workflow_dispatch:

jobs:
  send_notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: mentors
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: https://github.com/CodecoolBase/projectify-vscode-snippets/raw/main/images/logo.png
        SLACK_MESSAGE: 'Developing curriculum in Codecool is not the simplest thing to do as a mentor. With this code snippet collection I would like to help to make easier and more pleasant to create new content in our curriculum. :fiesta_parrot: <https://github.com/CodecoolBase/projectify-vscode-snippets/releases|Check the new version here>'
        SLACK_TITLE: Projectify VS Code snippets - NEW VERSION
        SLACK_USERNAME: attila.molnar
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
